apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-fjhn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-fjhn@sha256:fa15fd9db94f853e1cb0f4a9e6522cbeee8162eb90016884648913f0f6a61157
        name: my-python
        resources: {}
status: {}
