apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-mnj3
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-mnj3@sha256:6dfe3e65c7b4b3bfce2281b77c8fa3aaf56510f4642fa0b127c02b13b1b98e7a
        name: my-nodejs
        resources: {}
status: {}
